apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:  
  name: {{ .Release.Name }}-metrics
  labels:
    prometheus: kube-prometheus
    release: prometheus-operator
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: listnr-web
  namespaceSelector:
    matchNames:
    - sca-listnr-web
  endpoints:
  - port: http
    interval: 10s
