apiVersion: v1
kind: Service
metadata:
  name: {{ include "listnr-web.fullname" . }}
  labels:
    app: {{ include "listnr-web.station" . }}
    chart: {{ include "listnr-web.chartstation" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: http
      targetPort: http
  selector:
    app: {{ include "listnr-web.station" . }}
    release: {{ .Release.Name }}
